---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: output_vars  
    - name: create ec2 key
      ec2_key:
        name: vprofile-key
        region: eu-central-1
      register: key_out
    - name: save private key info
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600        
      when: key_out.changed
    - name: create SG grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: allow port 22 from everywhere
        region: eu-central-1
        vpc_id: "{{vpcid}}"
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 94.134.128.162/32
      register: BAstionSG_out
    - name: create Bastion host
      ec2:
        key_name: vprofile-key
        region: eu-central-1
        instance_type: t2.micro
        image: ami-00ad2436e75246bba
        wait: yes
        wait_timeout: 300
        instance_tags:
            Name: "Bastion_host"
            Project: Vprofile
            owner: Devops
        exact_count: 1
        count_tag:
            Name: "Bastion_host"
            Project: Vprofile
            owner: Devops        
        group_id: "{{BAstionSG_out.group_id}}"
      register: BH_out  
 