- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
	  include_vars: vars/vpc_setup

    - name: create vprofile VPC
	  ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
		cide_block: "{{vpcCidr}}"
		dns_support: yes
		dns_hostnames: yes
		tenancy: default
		state: "{{state}}"
      register: vpcout

    - debug:
        var: vpcout