- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup variable
      include_vars: ./vars/vpc_setup    
    - name: create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        region: "{{region}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - name: create pubsub1 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub1
      register: pubsub1_out            
    - name: create pubsub2 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub2
      register: pubsub2_out            
    - name: create pubsub3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub3
      register: pubsub3_out                  
    - name: create privsub1 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PrivSub1Cidr}}"
        resource_tags:
            Name: Vprofile-privsub1
      register: privsub1_out      
    - name: create privsub2 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PrivSub2Cidr}}"
        resource_tags:
            Name: Vprofile-privsub2
      register: privsub2_out      
    - name: create privsub3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PrivSub3Cidr}}"
        resource_tags:
            Name: Vprofile-privsub3
      register: privsub3_out 
    - name: Internet Gateway Group 
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
            Name: Vprofile-IGW
      register: igw_out            
    - name: Vprofile-Route 
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
            Name: Vprofile-PubRT        
        state: "{{state}}"
        subnets:
            - "{{pubsub1_out.subnet.id}}"
            - "{{pubsub2_out.subnet.id}}"  
            - "{{pubsub3_out.subnet.id}}"
        routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out                  
    - name: new NatGateway in public subnet 
      ec2_vpc_nat_gateway:
        wait: yes
        state: "{{state}}"
        subnet_id: "{{pubsub1_out.subnet.id}}"        
        region: "{{region}}"
        if_exist_do_not_create: true
      register: NATGW_out                  
    - name: Vprofile private Route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
            Name: Vprofile-PrivRT        
        subnets:
            - "{{privsub1_out.subnet.id}}"
            - "{{privsub2_out.subnet.id}}"  
            - "{{privsub3_out.subnet.id}}"
        routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{NATGW_out.nat_gateway_id}}"
      register: privRT_out 
    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id 
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw_out.gateway_id
        - pubRT_out.route_table.id
        - NATGW_out.nat_gateway_id
        - privRT_out.route_table.id
    - set_fact:
        vpcid: "{{vpcout.vpc.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubsub3id: "{{pubsub3_out.subnet.id}}"
        privsub1id: "{{privsub1_out.subnet.id}}"
        privsub2id: "{{privsub2_out.subnet.id}}"
        privsub3id: "{{privsub3_out.subnet.id}}"
        igwid: "{{igw_out.gateway_id}}"
        pubRTid: "{{pubRT_out.route_table.id}}"
        NATGWid: "{{NATGW_out.nat_gateway_id}}"
        privRTid: "{{privRT_out.route_table.id}}"
        cacheable: yes        
    - name: create variable file for VPC output
      copy:
        content: "vpcid: {{vpcout.vpc.id}} \npubsub1id: {{pubsub1_out.subnet.id}} \npubsub2id: {{pubsub2_out.subnet.id}} \npubsub3id: {{pubsub3_out.subnet.id}} \nprivsub1id: {{privsub1_out.subnet.id}} \nprivsub2id: {{privsub2_out.subnet.id}} \nprivsub3id: {{privsub3_out.subnet.id}} \nigwid: {{igw_out.gateway_id}} \npubRTid: {{pubRT_out.route_table.id}} \nNATGWid: {{NATGW_out.nat_gateway_id}} \nprivRTid: {{privRT_out.route_table.id}}"
        dest: output_vars