- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create vprofile VPC
      ec2_vpc_net:
        name: Vprofile-vpc
        region: eu-central-1
        cidr_block: 172.20.0.0/16
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: present
      register: vpcout
    - name: create pubsub1 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: eu-central-1
        az: eu-central-1a
        state: present
        cidr: 172.20.1.0/24
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub1
      register: pubsub1_out            
    - name: create pubsub2 
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: eu-central-1
        az: eu-central-1b
        state: present
        cidr: 172.20.2.0/24
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub2
      register: pubsub2_out            
    - name: create pubsub3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: eu-central-1
        az: eu-central-1c
        state: present
        cidr: 172.20.3.0/24
        map_public: yes
        resource_tags:
            Name: Vprofile-pubsub3
      register: pubsub3_out                  